export const weatherConditionData={    
    '01d': 'clearSkyDay', // Clear sky (day)
    '01n': 'ClearSkyNight', // Clear sky (night)
    '02d': 'fewCloudsDay', // Few clouds (day)
    '02n': 'fewCloudsNight', // Few clouds (night)
    '03d': 'scatteredCloudsDay', // Scattered clouds (day)
    '03n': 'scatteredCloudsNight', // Scattered clouds (night)
    '04d': 'brokenCloudsDay', // Broken clouds (day)
    '04n': 'brokenCloudsNight', // Broken clouds (night)
    '09d': 'showerRainDay', // Shower rain (day)
    '09n': 'showerRainNight', // Shower rain (night)
    '10d': 'rainDay', // Rain (day)
    '10n': 'rainNight', // Rain (night)
    '11d': 'thunderstormDay', // Thunderstorm (day)
    '11n': 'thunderStormNight', // Thunderstorm (night)
    '13d': 'snowDay', // Snow (day)
    '13n': 'snowNight', // Snow (night)
    '50d': 'mistDay', // Mist (day)
    '50n': 'mistNight' // Mist (night)
    };